package br.unipar.exretangulo;

import javax.swing.JOptionPane;

/**
 *
 * @author andersonbosing
 */
public class ContaCorrente {

    //CRIAR UMA CLASSE QUE REPRESENTE UMA CONTA CORRENTE
    //DEVE SE VERIFICAR OS ATRIBUTOS NECESSÁRIOS ALÉM DOS SEGUINTES OBRIGATÓRIOS
    //SALDO E LIMITE E OS METODOS SACAR, DEPOSITAR, IMPRIMIREXTRATO
    //DEVE SE ADICIONAR AS VALIDAÇÕES NECESSÁRIAS CONDIZENTES COM O FUNCIONAMENTO
    //DE UMA CONTA CORRENTE
    

}
